#!/bin/bash
#Converts two images to a interpolated image set.

image1=$1
image2=$2
outFolder=$3
frames=$(printf "%0.3f\n" $(echo "$4/30" | bc -l))
calculatedFrames=
tempFolder="$(mktemp -d)"
tempImageMovie="$(mktemp --suffix=.mp4)"
tempInterpolatedMovie="$(mktemp --suffix=.mp4)"

cp $image1 $tempFolder/i1.jpg
cp $image2 $tempFolder/i2.jpg

ffmpeg -i "$tempFolder/i%d.jpg" -r 30 -c:v libx264 -crf 0 -preset ultrafast -hide_banner "$tempImageMovie"

butterflow -l -s a=00.000,b=end,dur=$frames -o "$tempInterpolatedMovie" "$tempImageMovie"

ffmpeg -i "$tempInterpolatedMovie" -hide_banner "$outputFolder/img%04d.jpg"

rm -rf $tempFolder
rm $tempImageMovie
rm $tempInterpolatedMovie
